// Owner: Workflow Engineer
// All valid candidate states. Must match Prisma schema enum.

export const STATES = {
  APPLIED: 'APPLIED',
  CV_PARSING: 'CV_PARSING',
  CV_PARSE_FAILED: 'CV_PARSE_FAILED',
  CV_UNDER_REVIEW: 'CV_UNDER_REVIEW',
  CV_REJECTED: 'CV_REJECTED',
  AI_INTERVIEW_INVITED: 'AI_INTERVIEW_INVITED',
  AI_INTERVIEW_IN_PROGRESS: 'AI_INTERVIEW_IN_PROGRESS',
  AI_INTERVIEW_COMPLETED: 'AI_INTERVIEW_COMPLETED',
  AI_INTERVIEW_SCORED: 'AI_INTERVIEW_SCORED',
  INTERVIEW_PENDING: 'INTERVIEW_PENDING',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  INTERVIEW_INVITE_FAILED: 'INTERVIEW_INVITE_FAILED',
  INTERVIEW_DONE: 'INTERVIEW_DONE',
  INTERVIEW_REJECTED: 'INTERVIEW_REJECTED',
  OFFER_GENERATING: 'OFFER_GENERATING',
  OFFER_SENT: 'OFFER_SENT',
  ONBOARDING: 'ONBOARDING',
  HIRED: 'HIRED',
  FAILED: 'FAILED',
  INTERVIEW_CONFIRMED: 'INTERVIEW_CONFIRMED',
  INTERVIEW_RESCHEDULE_REQUESTED: 'INTERVIEW_RESCHEDULE_REQUESTED',
} as const;

export type State = (typeof STATES)[keyof typeof STATES];

export const TERMINAL_STATES: State[] = [
  STATES.CV_REJECTED,
  STATES.INTERVIEW_REJECTED,
  STATES.HIRED,
  STATES.FAILED,
];
